name: Check

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - '*'
  pull_request: {}

jobs:

  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet

      - name: Test
        run: go test -v ./...

      - name: Format check
        run: |
          fmtdiff="$(gofmt -s -e -d .)"
          if [ -n "$fmtdiff" ]; then
            >&2 echo "$fmtdiff"
            exit 1
          fi

      - name: Mod tidy
        run: |
          go mod tidy
          git diff --exit-code

  terraform-docs:
    name: Terraform docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check docs updated
        run: |
          go generate tools/tools.go
          tfplugindocs --version
          tfplugindocs generate
          change="$(git diff)"
          if [ -n "$change" ]; then
            >&2 echo "$change"
            exit 1
          fi

  terraform-examples:
    name: Terraform examples
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Terraformat
        run: terraform fmt -recursive examples

      - name: Check examples
        run: make examples
